import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import HeaderSection from "@/components/layout/header";
import FooterSection from "@/components/layout/footer";

const rethinkSans = localFont({
  src: "./fonts/RethinkSans.woff",
  variable: "--font-rethink-sans",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      style={{ ...rethinkSans.style }}
      className="bg-black"
    >
      <body className="relative max-w-[1920px] mx-auto">
        <HeaderSection />
        {children}
        <FooterSection />
      </body>
    </html>
  );
}
